### ISSUE TITLE
Suggestion: Output Screenshot

### ISSUE THREAD

**Issue by CodeYan01** [synap5e/obs-screenshot-plugin#14]
Hey, this plugin is really great. But when I have many scenes and I need to pick which to screenshot, it's really impractical to set hotkeys for each scene. Please consider adding a feature to capture the output.

**Comment by synap5e** [comment]
Hi

Unfortunately I believe this is not possible, since this plugin acts as a filter on a single source/scene, rather than the output, and I don't think hotkeys can overlap.

There is a new "screenshot canvas" feature that was added to OBS recently https://github.com/obsproject/obs-studio/pull/3202 which I am fairly sure will be in the next release.
