### ISSUE TITLE
URL PUT not working

### ISSUE THREAD

**Issue by coneos** [synap5e/obs-screenshot-plugin#26]
Hi,
Great plugin but I have to save first locally and then send the screenshots via a batch because the send to URL doesn't work.
I don't see any request to the URL in Wireshark and I have no idea how to debug.
Any idea please?

**Comment by synap5e** [comment]
Can you check the OBS log - there should be a few messages from this plugin there

**Comment by johnzuidweg** [comment]
I suppose this issue is related to [this one](https://github.com/synap5e/obs-screenshot-plugin/issues/18). I think https://github.com/synap5e/obs-screenshot-plugin/blob/master/screenshot-filter.c#L755 should be `host_start += 3;`

Also I suppose the https check that start on https://github.com/synap5e/obs-screenshot-plugin/blob/master/screenshot-filter.c#L777 should be modified in order for it to work. And it could be improved by generalising it so that it also works if a port is specified.

I'll do a pull request for both issues.

**Comment by synap5e** [comment]
Fixed in #32
